local js = require "tests.testlibs"
js.__prepare_environment()
local a = Number(1)
local b = Number(2)
assert(__javascript_toBoolean(a == Number(1)) , "arithmetics.js", 5)
assert(__javascript_toBoolean(b == Number(3)) , "arithmetics.js", 6)
a = __javascript_toNumeric(a) - __javascript_toNumeric(Number(3))
assert(__javascript_toBoolean(a == Number(-2)) , "arithmetics.js", 10)
b = __javascript_toNumeric(b) * __javascript_toNumeric(__javascript_add(a, Number(1)))
assert(__javascript_toBoolean(b == Number(-4)) , "arithmetics.js", 12)
a = __javascript_add(a, b)
assert(__javascript_toBoolean(a == Number(-6)) , "arithmetics.js", 14)
a = __javascript_toNumeric(a) / __javascript_toNumeric(Number(3))
assert(__javascript_toBoolean(a == Number(-2)) , "arithmetics.js", 16)
a = __javascript_toNumeric(a) * __javascript_toNumeric(Number(-1))
assert(__javascript_toBoolean(a == Number(2)) , "arithmetics.js", 18)
a = __javascript_toNumeric(a) % __javascript_toNumeric(Number(3))
assert(__javascript_toBoolean(a == Number(1)) , "arithmetics.js", 20)
a = __javascript_toNumeric(a) // (2 ^ __javascript_toNumeric(Number(2)))
assert(__javascript_toBoolean(a == Number(4)) , "arithmetics.js", 22)
a = __javascript_toNumeric(a) ^ __javascript_toNumeric(Number(2))
assert(__javascript_toBoolean(a == Number(8)) , "arithmetics.js", 24)
a = __javascript_toNumeric(a) << __javascript_toNumeric(Number(1))
assert(__javascript_toBoolean(a == Number(4)) , "arithmetics.js", 26)
a = __javascript_toNumeric(a) | __javascript_toNumeric(Number(1))
assert(__javascript_toBoolean(a == Number(5)) , "arithmetics.js", 28)
a = __javascript_toNumeric(a) & __javascript_toNumeric(Number(3))
assert(__javascript_toBoolean(a == Number(1)) , "arithmetics.js", 30)
a=Number(2)
b=Number(3)
local c
c=__javascript_add(a, b)
assert(__javascript_toBoolean(c == Number(5)) , "arithmetics.js", 38)
c=(__javascript_toNumeric(Number(2)) * __javascript_toNumeric(Number(3))) 
assert(__javascript_toBoolean(c == Number(6)) , "arithmetics.js", 40)
c=(__javascript_toNumeric(a) / __javascript_toNumeric(Number(4))) 
assert(__javascript_toBoolean(c == Number(5)) , "arithmetics.js", 42)
c=( __javascript_toNumeric(c) ^ __javascript_toNumeric(Number(3))) 
assert(__javascript_toBoolean(c == Number(41.666666666666664)) , "arithmetics.js", 44)
c=__javascript_add(( __javascript_toNumeric(((__javascript_toNumeric(Number(2)) << __javascript_toNumeric(Number(6))) )) ^ __javascript_toNumeric(Number(5))) , (__javascript_toNumeric(Number(1)) * __javascript_toNumeric(Number(2))) )
assert(__javascript_toBoolean(c == Number(10)) , "arithmetics.js", 46)
c=(__javascript_toNumeric(c) & __javascript_toNumeric(Number(24)))
assert(__javascript_toBoolean(c == Number(8)) , "arithmetics.js", 48)
